-- ============================================================
-- SEED COMPLETO v6 — OPRPG Tools
-- Dados 100% extraídos e verificados dos PDFs oficiais:
-- Livro Base (LB), Sobrevivendo ao Horror (SaH),
-- Arquivos Secretos Fevereiro (AS-FEV)
-- ============================================================

TRUNCATE creatures, rituals, items, powers, origins RESTART IDENTITY CASCADE;

-- ============================================================
-- CRIATURAS
-- ============================================================

INSERT INTO creatures (slug, name, element, vd, size, creature_type,
  agi, for_, int_, pre, vig, pv, pv_machucado, defesa,
  fort, reflex, vontade, movement,
  pp_dt, pp_damage, pp_immunity_nex,
  resistances, vulnerabilities, immunities,
  abilities, description, source) VALUES
(
  'sepultado', 'Sepultado', 'morte', 20, 'grande', 'criatura',
  0, 3, 0, 0, 3,
  50, 25, 16,
  '1d20', '1d20', '1d20', 9,
  15, '2d4 mental', 25,
  'Balístico, corte, impacto e perfuração 5', 'Energia', NULL,
  '[]',
  'Criatura composta por múltiplos corpos selados juntos, emitindo um barulho repetitivo de tambor.', 'SaH'),
(
  'mescla', 'Mescla', 'sangue', 60, 'grande', 'criatura',
  2, 2, 0, 1, 3,
  100, 50, 21,
  '3d20+10', '1d20+5', '1d20', 9,
  20, '3d6 mental', 35,
  'Balístico, impacto e perfuração 5, Sangue 10', 'Morte e fogo', NULL,
  '[]',
  'Criatura de Sangue grotesca formada pela fusão de múltiplos corpos, com odor nauseante.', 'SaH'),
(
  'o-uivar', 'O Uivar', 'energia', 100, 'médio', 'criatura',
  0, 0, 0, 0, 3,
  100, 50, 20,
  '1d20+5', '3d20+10', '3d20+10', 9,
  20, '4d6 mental', 45,
  NULL, 'Morte', NULL,
  '[]',
  'Anomalia paranormal que se manifesta como uma entidade climática de Energia incontrolável.', 'SaH'),
(
  'derretido', 'Derretido', 'sangue', 80, 'enorme', 'criatura',
  1, 3, 0, 0, 3,
  140, 70, 23,
  '4d20+10', '1d20+5', '1d20+5', 9,
  20, '4d6 mental', 40,
  'Sangue 20', 'Morte, fogo e químico', 'Balístico, corte, impacto e perfuração',
  '[]',
  'Criatura de Sangue sem forma sólida, que se move através de superfícies como líquido.', 'SaH'),
(
  'melancolia', 'Melancolia', 'conhecimento', 140, 'minúsculo', 'criatura',
  2, 1, 3, 3, 2,
  200, 100, 29,
  '3d20+5', '2d20+10', '4d20+15', 6,
  25, '4d8 mental', 50,
  NULL, 'Energia', NULL,
  '[]',
  'Parasita de Conhecimento que infecta gradualmente sua vítima, deformando seu rosto em tristeza permanente.', 'SaH'),
(
  'quibungo', 'Quibungo', 'sangue', 160, 'grande', 'criatura',
  4, 4, 1, 2, 4,
  320, 160, 34,
  '4d20+10', '4d20+10', '2d20+5', 15,
  25, '4d8 mental', 55,
  'Balístico, impacto, perfuração e Sangue 20', 'Morte', NULL,
  '[]',
  'Criatura de Sangue da mitologia afro-brasileira: gigante com uma abertura nas costas onde devora crianças.', 'SaH'),
(
  'profundo', 'Profundo', 'energia', 200, 'enorme', 'criatura',
  3, 4, 1, 2, 4,
  380, 190, 34,
  '2d20+10', '4d20+15', '2d20+10', 6,
  30, '6d6 mental', 65,
  'Balístico, corte, impacto, perfuração, Energia e Sangue 20', 'Morte e fogo', NULL,
  '[]',
  'Criatura de Energia que habita as profundezas oceânicas, semelhante a um cefalópode colossal.', 'SaH'),
(
  'memento-mori', 'Memento Mori', 'morte', 260, 'médio', 'criatura',
  1, 1, 3, 3, 3,
  650, 325, 44,
  '4d20+20', '2d20+15', '4d20+20', 9,
  35, '8d6 mental', 80,
  'Balístico, corte, impacto, perfuração e Morte 20', 'Energia', NULL,
  '[]',
  'Criatura de Morte que se alimenta de memórias e da noção de mortalidade, tornando-se cada vez mais poderosa.', 'SaH'),
(
  'rascunho', 'Rascunho', 'conhecimento', 300, 'médio', 'criatura',
  3, 2, 5, 5, 3,
  750, 375, 48,
  '4d20+20', '3d20+15', '5d20+25', 18,
  35, '7d8 mental', 90,
  'Balístico, corte, impacto, perfuração, Conhecimento e Energia 20', 'Sangue', NULL,
  '[]',
  'Criatura de Conhecimento que parece um esboço inacabado de realidade, capaz de reescrever a si mesma.', 'SaH'),
(
  'medusa', 'Medusa', 'conhecimento', 320, 'grande', 'criatura',
  3, 3, 4, 4, 3,
  380, 190, 50,
  '4d20+20', '4d20+20', '5d20+25', 12,
  40, '9d6 mental', 95,
  'Corte, impacto, perfuração e Morte 20', 'Sangue', 'Conhecimento',
  '[]',
  'Releitura paranormal da Medusa mítica: criatura de Conhecimento capaz de petrificar com o olhar.', 'SaH'),
(
  'amigo-imaginario', 'Amigo Imaginário', 'morte', 360, 'grande', 'criatura',
  5, 5, 3, 5, 4,
  1000, 500, 56,
  '4d20+20', '5d20+30', '5d20+30', 12,
  40, '8d8 mental', NULL,
  'Balístico, corte, impacto e perfuração 20', 'Energia', 'Morte, Sangue',
  '[]',
  'Criatura de Morte que se alimenta do medo e da imaginação infantil, assumindo a forma de um amigo distorcido.', 'SaH'),
(
  'o-terminal', 'O Terminal', 'morte', 260, 'colossal', 'criatura',
  0, 5, 2, 4, 5,
  700, 350, 28,
  '4d20+15', NULL, '4d20+20', 15,
  30, '8d6 mental', 85,
  'Balístico, impacto e perfuração 10, Morte 20', 'Energia', NULL,
  '[]',
  'Criatura colossal de Morte que habita estações de metrô abandonadas, formada por tentáculos de Lodo.', 'LB'),
(
  'enpap-x', 'Enpap-X', 'sangue', 180, 'grande', 'criatura',
  2, 4, 1, 2, 3,
  360, 180, 36,
  '3d20+15', '2d20+15', '2d20+10', 12,
  25, '6d6 mental', 60,
  'Balístico, impacto e perfuração 10, Sangue 20', 'Morte', NULL,
  '[]',
  'Criatura de Sangue originada da Suméria antiga. Humanoide enorme de quatro braços com correntes, movida por ódio eterno.', 'AS-FEV'),
(
  'kerberos', 'Kerberos', 'sangue', 340, 'enorme', 'criatura',
  4, 5, 0, 3, 5,
  1150, 575, 46,
  '4d20+20', '3d20+15', '3d20+15', 18,
  35, '10d6 mental', 99,
  'Balístico, impacto, perfuração e Sangue 20', 'Morte', NULL,
  '[]',
  'O cão de três cabeças. Criatura de Sangue colossal que só pode ser manifestada em um Inferno — área paranormal tomada pelo Sangue.', 'AS-FEV'),
(
  'minotauro-de-sangue', 'Minotauro de Sangue', 'sangue', 280, 'grande', 'criatura',
  4, 5, 1, 3, 5,
  750, 375, 44,
  '5d20+20', '4d20+15', '3d20+10', 12,
  35, '8d6 mental', 80,
  'Balístico, impacto, perfuração e Sangue 20', 'Morte', NULL,
  '[]',
  'Criatura de Sangue bípede enorme infectada com pústulas de sangue. Furioso e implacável.', 'AS-FEV'),
(
  'mulher-afogada', 'Mulher Afogada', 'sangue', 140, 'médio', 'criatura',
  4, 3, 2, 2, 3,
  240, 120, 28,
  '3d20+10', '4d20+10', '2d20+5', 9,
  25, '4d8 mental', 50,
  'Balístico, Energia, impacto e perfuração 10, Sangue 20', 'Morte', NULL,
  '[]',
  'Criatura de Sangue que pode assumir forma líquida. Invade orifícios da vítima, afogando-a em sangue.', 'AS-FEV'),
(
  'tita-de-sangue', 'Titã de Sangue', 'sangue', 220, 'enorme', 'criatura',
  2, 5, 1, 1, 4,
  550, 275, 35,
  '4d20+15', '2d20+10', '1d20+10', 12,
  30, '7d6 mental', 70,
  'Balístico, impacto, perfuração e Sangue 20', 'Morte', NULL,
  '[]',
  'Criatura de Sangue de três metros, musculatura pulsante de veias expostas. Estraçalha tudo em sua frente.', 'AS-FEV'),
(
  'zumbi-de-sangue-bestial', 'Zumbi de Sangue Bestial', 'sangue', 100, 'grande', 'criatura',
  2, 3, 0, 2, 3,
  200, 100, 23,
  '3d20+10', '2d20+5', '2d20+5', 12,
  20, '4d6 mental', 45,
  'Balístico, impacto e perfuração 5, Sangue 10', 'Morte', NULL,
  '[]',
  'Forma mais perigosa do Zumbi de Sangue: maior, mais rápida e letal, com comportamento furtivo.', 'AS-FEV'),
(
  'o-diabo', 'O Diabo', 'sangue', 400, 'médio', 'criatura',
  6, 6, 6, 6, 6,
  1666, 833, 66,
  '6d20+35', '6d20+35', '6d20+35', 18,
  45, '10d8 mental', NULL,
  'Balístico, impacto e perfuração 20', 'Morte', 'Atordoado, condições de paralisia, dano e efeitos de Sangue',
  '[]',
  'A entidade mais poderosa do Sangue. Faz pactos e pode aparecer a pessoas normais escolhendo não ativar sua PP.', 'AS-FEV'),
(
  'aracnasita', 'Aracnasita', 'morte', 80, 'grande', 'criatura',
  3, 3, 1, 1, 3,
  140, 70, 23,
  '2d20+5', '3d20+10', '1d20+5', 12,
  20, '4d6 mental', 40,
  'Balístico, corte, impacto, perfuração e Morte 20', 'Energia e fogo', NULL,
  '[]',
  'Criatura de Morte semelhante a uma aranha gigante. Captura vítimas em casulos que se tornam novos ovos.', 'AS-FEV'),
(
  'carnical-preto-da-morte', 'Carniçal Preto da Morte', 'morte', 200, 'médio', 'criatura',
  4, 4, 3, 3, 3,
  400, 200, 38,
  '3d20+15', '4d20+15', '3d20+15', 12,
  30, '6d6 mental', 65,
  'Corte, impacto e perfuração 10, Morte 20', 'Energia', 'Balístico',
  '[]',
  'Criatura de Morte e Conhecimento com físico paranormal. Rastreia e elimina alvos com eficiência aterrorizante.', 'AS-FEV'),
(
  'ceifador-espiral', 'Ceifador Espiral', 'morte', 380, 'grande', 'criatura',
  5, 5, 5, 5, 5,
  999, 499, 58,
  '5d20+25', '5d20+25', '5d20+25', 15,
  45, '9d8 mental', NULL,
  'Dano 50', 'Energia', 'Condições de paralisia e dano e efeitos de Morte',
  '[]',
  'A própria Morte personificada. Decepamentos críticos reduzem a vítima a 25 PV e causam perda permanente de atributo.', 'AS-FEV'),
(
  'enraizado', 'Enraizado', 'morte', 120, 'médio', 'criatura',
  3, 3, 1, 1, 3,
  140, 70, 28,
  '3d20+10', '3d20+10', '1d20+5', 9,
  20, '4d6 mental', 50,
  'Corte, impacto e perfuração 10, Morte 20', 'Energia', NULL,
  '[]',
  'Criatura de Morte que se instala em locais de alta concentração paranormal, fundindo-se com o ambiente.', 'AS-FEV'),
(
  'estrangeiro', 'Estrangeiro', 'conhecimento', 340, 'grande', 'criatura',
  3, 5, 5, 5, 3,
  750, 375, 50,
  '3d20+15', '3d20+20', '5d20+25', 15,
  40, '10d6 mental', 99,
  NULL, 'Sangue', 'Dano',
  '[]',
  'Entidade de Conhecimento e Energia de origem alienígena. Comanda outras criaturas e possui intelecto elevadíssimo.', 'AS-FEV'),
(
  'existido', 'Existido', 'conhecimento', 20, 'médio', 'criatura',
  2, 1, 2, 2, 2,
  36, 18, 13,
  '1d20', '1d20+5', '2d20+10', 9,
  14, '1d6 mental', 25,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Conhecimento que mal existe na Realidade. Pode se fortalecer temporariamente com poder paranormal.', 'AS-FEV'),
(
  'lembrado', 'Lembrado', 'conhecimento', 100, 'médio', 'criatura',
  2, 2, 3, 4, 2,
  180, 90, 22,
  '2d20+5', '2d20', '2d20+10', 9,
  20, '4d6 mental', 45,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Conhecimento formada por alguém com alta exposição paranormal. Emite aura dourada de faces gritando.', 'AS-FEV'),
(
  'ocioso', 'Ocioso', 'conhecimento', 260, 'grande', 'criatura',
  1, 2, 4, 5, 2,
  390, 195, 37,
  '3d20+15', '1d20', '5d20+20', 9,
  35, '8d6 mental', 80,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Conhecimento que aterroriza apenas com sua presença estática e olhar vazio. Escolhe uma vítima e a persegue.', 'AS-FEV'),
(
  'parasita-de-culpa', 'Parasita de Culpa', 'conhecimento', 246, 'médio', 'criatura',
  2, 1, 3, 3, 3,
  90, 45, 15,
  '1d20+10', '2d20+10', '4d20+10', 9,
  20, '2d6 mental', 35,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Conhecimento que se alimenta da culpa e traumas do hospedeiro, crescendo junto com seus medos.', 'AS-FEV'),
(
  'rastejador-sombrio', 'Rastejador Sombrio', 'conhecimento', 180, 'médio', 'criatura',
  4, 3, 3, 3, 3,
  330, 165, 41,
  '3d20+15', '4d20+15', '3d20+10', 12,
  25, '6d6 mental', 60,
  'Balístico, corte e impacto 10, Conhecimento 20', 'Sangue', NULL,
  '[]',
  'Criatura de Conhecimento e Sangue furtiva. Vulnerável à luz — perde habilidades especiais ao ser iluminada.', 'AS-FEV'),
(
  'silhueta', 'Silhueta', 'conhecimento', 360, 'médio', 'criatura',
  4, 4, 5, 5, 4,
  500, 250, 55,
  '4d20+20', '4d20+20', '5d20+25', 12,
  40, '8d8 mental', NULL,
  'Dano 30', 'Sangue', 'Condições de paralisia e dano e efeitos de Conhecimento e manobras de combate',
  '[]',
  'Criatura que atingiu o Outro Lado pelo Conhecimento puro. Tudo que a toca sofre dano massivo.', 'AS-FEV'),
(
  'vulto', 'Vulto', 'conhecimento', 40, 'médio', 'criatura',
  4, 2, 2, 2, 1,
  60, 30, 19,
  '1d20', '4d20+5', '2d20+5', 9,
  15, '3d6 mental', 30,
  'Balístico, corte e perfuração 5, Conhecimento 10', 'Sangue', NULL,
  '[]',
  'Criatura de Conhecimento quase imperceptível. Existe em locais com Membrana danificada, confundindo realidade e paranormal.', 'AS-FEV'),
(
  'mascara-do-desespero', 'Máscara do Desespero', 'conhecimento', 254, 'minúsculo', 'relíquia',
  4, 4, 6, 6, 5,
  1200, 600, 55,
  '5d20+35', '4d20+25', '6d20+35', 0,
  45, '10d8 mental', NULL,
  NULL, 'Sangue', 'Condições e dano',
  '[]',
  'Relíquia de Conhecimento. Onipresente na Realidade, é a única capaz de resolver o Enigma de Medo do Anfitrião.', 'AS-FEV'),
(
  'anarquico-descontrolado', 'Anárquico Descontrolado', 'energia', 120, 'médio', 'criatura',
  3, 3, 2, 2, 2,
  120, 60, 28,
  '3d20+10', '4d20+10', '2d20+5', 9,
  21, '4d6 mental', 50,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Energia instável que ataca aleatoriamente. Comportamento imprevisível — até ela mesma pode ser afetada.', 'AS-FEV'),
(
  'anomiatico', 'Anomiático', 'energia', 240, 'médio', 'criatura',
  4, 3, 2, 3, 4,
  600, 300, 41,
  '5d20+20', '5d20+20', '4d20+15', 9,
  30, '6d8 mental', 75,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Energia cujo comportamento é regido pelo fluxo caótico em seu corpo. Garras que desintegram matéria.', 'AS-FEV'),
(
  'ciborgue', 'Ciborgue', 'energia', 80, 'grande', 'criatura',
  3, 3, 2, 2, 3,
  160, 80, 25,
  '3d20+5', '3d20+5', '2d20', 9,
  15, '2d6 mental', 40,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Energia que alterna entre estados de combate. Programada para eliminar ameaças à Membrana.', 'AS-FEV'),
(
  'infecticidio', 'Infecticídio', 'energia', 280, 'enorme', 'criatura',
  2, 5, 1, 1, 5,
  600, 300, 25,
  '5d20+20', '3d20', '1d20+15', 9,
  35, '8d6 mental', 85,
  NULL, NULL, NULL,
  '[]',
  'Horda de criaturas infectadas por vírus de Energia. Infecção se espalha por contato com seus ataques.', 'AS-FEV'),
(
  'sukkalgir', 'Sukkalgir', 'conhecimento', 160, 'médio', 'criatura',
  3, 3, 3, 3, 3,
  220, 110, 34,
  '3d20+10', '3d20+10', '3d20+15', 9,
  25, '4d8 mental', 55,
  NULL, NULL, NULL,
  '[]',
  'Alma torturada através do fogo, originada da antiga Suméria. Emana desespero e dor em torno de si.', 'AS-FEV'),
(
  'tempestuoso', 'Tempestuoso', 'energia', 360, 'médio', 'criatura',
  5, 4, 2, 5, 4,
  950, 475, 56,
  '4d20+20', '5d20+30', '5d20+25', 9,
  40, '8d8 mental', NULL,
  'Balístico, corte, perfuração e Energia 20', 'Conhecimento', 'Condições de paralisia',
  '[]',
  'Criatura de Energia formada em locais com Membrana extremamente danificada. Aura radioativa devastadora.', 'AS-FEV'),
(
  'anfitriao', 'Anfitrião', 'energia', 278, 'médio', 'criatura',
  7, 5, 6, 6, 5,
  1413, 706, 59,
  '7d20+35', '7d20+35', '6d20+25', 9,
  45, '10d8 mental', NULL,
  NULL, 'Conhecimento', 'Condições de paralisia, dano e efeitos de Energia',
  '[]',
  'Caos ilógico personificado. Único capaz de enfrentar o Deus da Morte. Possui Enigma de Medo único.', 'AS-FEV'),
(
  'degolificada', 'Degolificada', 'energia', 282, 'médio', 'criatura',
  4, 3, 3, 4, 3,
  850, 425, 45,
  '4d20+20', '3d20+15', '4d20+25', 9,
  40, '9d6 mental', 95,
  NULL, NULL, NULL,
  '[]',
  'Criatura com múltiplos elementos. Usa longos cabelos como armas para penetrar orifícios faciais. Imune a dano até resolução do mistério.', 'AS-FEV'),
(
  'escutado', 'Escutado', 'morte', 160, 'médio', 'criatura',
  3, 3, 2, 2, 3,
  290, 145, 29,
  '3d20+10', '4d20+10', '2d20+5', 9,
  25, '4d8 mental', 55,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Morte originada de alguém que escutou a Melodia do Escutado. Replica sons perturbadores ao redor.', 'AS-FEV'),
(
  'esqueleto-de-lodo', 'Esqueleto de Lodo', 'morte', 20, 'médio', 'criatura',
  2, 2, 0, 1, 1,
  40, 20, 14,
  '1d20', '2d20+5', '1d20', 6,
  14, '2d4 mental', 25,
  'Corte, impacto e perfuração 5, Morte 10', 'Energia', NULL,
  '[]',
  'Esqueleto reanimado por Lodo de Morte. Imortal — quando destruído, retorna em 1d3 rodadas com 20 PV.', 'AS-FEV'),
(
  'marionete', 'Marionete', 'morte', 280, 'médio', 'criatura',
  3, 3, 2, 4, 3,
  700, 350, 40,
  '2d20+10', '3d20+15', '5d20+20', 9,
  35, '8d6 mental', 85,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Morte que controla corpos como fantoches. Não pode ter seu deslocamento reduzido.', 'AS-FEV'),
(
  'mumia-xipofaga', 'Múmia Xipófaga', 'morte', 240, 'médio', 'criatura',
  5, 4, 2, 3, 4,
  400, 200, 35,
  '4d20+15', '5d20+15', '3d20+10', 9,
  30, '6d8 mental', 75,
  'Corte, impacto e perfuração 10, Morte 20', 'Energia e fogo', NULL,
  '[]',
  'Múmia siamesa de Morte. Quando reduzida a 0 PV, continua agindo por suas Faixas da Permanência.', 'AS-FEV'),
(
  'nidere', 'Nidere', 'morte', 320, 'grande', 'criatura',
  4, 5, 2, 3, 4,
  800, 400, 50,
  '5d20+25', '5d20+25', '4d20+15', 12,
  35, '8d6 mental', 95,
  'Corte, impacto, perfuração e Morte 20', NULL, NULL,
  '[]',
  'Criatura de Morte de origem celta. Garras invertidas e movimentos impossíveis tornam-na aterrorizante.', 'AS-FEV'),
(
  'sempiternal', 'Sempiternal', 'morte', 360, 'médio', 'criatura',
  5, 5, 4, 5, 4,
  990, 495, 53,
  '4d20+20', '5d20+30', '5d20+25', 9,
  40, '8d8 mental', NULL,
  'Corte, impacto e perfuração 20', 'Energia', 'Condições de paralisia e dano e efeitos de Morte',
  '[]',
  'Criatura de Morte que acelera o envelhecimento com seu toque. Projeta vinhas de Lodo pelo chão.', 'AS-FEV'),
(
  'succ', 'Succ', 'morte', 40, 'médio', 'criatura',
  4, 2, 0, 1, 1,
  65, 32, 20,
  '1d20', '4d20+10', '1d20+5', 9,
  15, '3d6 mental', 30,
  'Corte, impacto e perfuração 5, Morte 10', 'Energia', NULL,
  '[]',
  'Pequena criatura de Morte que prende seus dentes no rosto da vítima e suga o ar de seus pulmões.', 'AS-FEV'),
(
  'perturbado-de-energia', 'Perturbado de Energia', 'conhecimento', 340, 'grande', 'criatura',
  3, 5, 5, 5, 3,
  750, 375, 50,
  '3d20+15', '3d20+20', '5d20+25', 15,
  40, '10d6 mental', 99,
  NULL, 'Sangue', 'Dano',
  '[]',
  'Manifestação extrema de Conhecimento e Energia. Capacidade de comandar e controlar outras criaturas.', 'AS-FEV'),
(
  'o-deus-da-morte', 'O Deus da Morte', 'morte', 400, 'grande', 'relíquia',
  6, 6, 5, 5, 7,
  2000, 1000, 60,
  '7d20+35', '6d20+35', '5d20+35', 15,
  45, '10d8 mental', NULL,
  'Corte, impacto e perfuração 20', 'Energia', 'Atordoado, condições de paralisia, dano e efeitos de Morte',
  '[]',
  'Manipulador temporal supremo. Recupera 50 PV por turno. Quando destruído, ressurge em cadáver próximo.', 'AS-FEV'),
(
  'anjo', 'Anjo', 'conhecimento', 380, 'enorme', 'criatura',
  4, 5, 5, 5, 5,
  1111, 555, 57,
  '5d20+25', '4d20+25', '5d20+30', 24,
  40, '10d6 mental', NULL,
  'Dano 50', 'Sangue', 'Condições de paralisia e dano e efeitos de Conhecimento',
  '[]',
  'Fisicalização do Conhecimento. Julga o saber dos mortais e causa dano mental proporcional ao dano de Conhecimento.', 'AS-FEV'),
(
  'bicho-papao', 'Bicho-papão', 'conhecimento', 300, 'médio', 'criatura',
  4, 4, 3, 4, 3,
  750, 375, 41,
  '4d20+15', '5d20+25', '5d20+20', 9,
  35, '7d8 mental', 90,
  NULL, NULL, NULL,
  '[]',
  'Criatura de Conhecimento inteligente que se comunica com vítimas através do medo. Vulnerável a cantigas de ninar.', 'AS-FEV'),
(
  'espreitador', 'Espreitador', 'conhecimento', 220, 'médio', 'criatura',
  4, 2, 3, 3, 2,
  500, 250, 34,
  '2d20+10', '4d20+15', '3d20+15', 9,
  30, '7d6 mental', 70,
  NULL, 'Sangue', 'Dano',
  '[]',
  'Criatura de Conhecimento com dezenas de olhos. Escolhe uma vítima para espreitar; só pode ser derrotado por ela.', 'AS-FEV');

-- ============================================================
-- RITUAIS — DADOS CANÔNICOS DO LIVRO BASE
-- ============================================================

INSERT INTO rituals (slug, name, element, circle, execution, range, target, area, duration, resistance, pe_cost, description, source) VALUES
('alterar-destino', 'Alterar Destino', 'energia', 4, 'reação', 'pessoal', 'você', NULL, 'instantânea', NULL, 8, 'Você vislumbra seu futuro próximo, analisando mi- lhões de possibilidades e escolhendo a melhor. Você recebe +15 em um teste de resistência ou na Defesa contra um ataque.', 'LB'),
('alterar-memoria', 'Alterar Memória', 'conhecimento', 3, 'padrão', 'toque', '1 pessoa', NULL, 'instantânea', 'Vontade anula', 6, 'Você invade a mente do alvo e altera ou apaga suas memórias de até uma hora atrás. Se escolher alterar as memórias, você pode mudar detalhes de eventos recentes, como a identidade de alguém encontrado ou o endereço de um lugar visitado, mas não reescrever completamente esses eventos. O alvo recupera suas memórias após 1d4 dias.', 'LB'),
('amaldicoar-tecnologia', 'Amaldiçoar Tecnologia', 'energia', 1, 'padrão', 'toque', '1 acessório ou arma de', NULL, 'cena', 'Vontade parcial', 2, 'Uma aura espiralada surge sobre o alvo. No início de cada turno dele, ele deve fazer um teste de Vontade. Se falhar, não poderá se deslocar naquele turno (ele ainda pode agir, só não pode se deslocar). Se o alvo passar nesse teste dois turnos seguidos o efeito termina.', 'LB'),
('aprimorar-fisico', 'Aprimorar Físico', 'sangue', 2, 'padrão', 'toque', '1 ser', NULL, 'cena', NULL, 4, 'O alvo tem seus músculos tonificados e seus liga- mentos reforçados, recebendo +1 em Agilidade ou Força, à escolha dele.', 'LB'),
('aprimorar-mente', 'Aprimorar Mente', 'conhecimento', 2, 'padrão', 'toque', '1 ser', NULL, 'cena', NULL, 4, 'O alvo tem sua mente energizada por fagulhos do Conhecimento. Ele recebe +1 em Intelecto ou Presença, à escolha dele (PE, perícias treinadas ou graus de treinamento). muda o bônus para +2. Requer', 'LB'),
('arma-atroz', 'Arma Atroz', 'sangue', 1, 'padrão', 'toque', '1 arma corpo a corpo', NULL, 'sustentada', NULL, 2, 'A arma é recoberta por veias carmesim e passa a exalar uma aura de violência. Ela fornece +2 em testes de ataque e +1 na margem de ameaça.', 'LB'),
('armadura-de-sangue', 'Armadura de Sangue', 'sangue', 1, 'padrão', 'pessoal', 'você', NULL, 'cena', NULL, 2, 'Seu sangue escorre para fora do corpo, cobrindo-o sob a forma de uma carapaça que fornece +5 em Defesa. Esse bônus é cumulativo com outros rituais, mas não com bônus fornecido por equipamento.', 'LB'),
('canalizar-o-medo', 'Canalizar o Medo', 'medo', 4, 'padrão', 'toque', '1 pessoa', NULL, 'permanen te até ser', 'Vontade parcial', 8, 'Você desperta uma paixão doentia e obcecada por você no alvo, que passa a querar agradá-lo a todo custo, mesmo que para isso precise ficar contra seus amigos. No início de cada turno do alvo ele deve fazer um teste de Vontade. Se falhar, age de forma a ajudá-lo na melhor de suas capacidades naquele turno. Se o alvo passar nesse teste dois turnos seguidos o efeito termina. 125', 'LB'),
('chamas-do-caos', 'Chamas do Caos', 'energia', 2, 'padrão', 'curto', 'veja texto', NULL, 'cena', 'Reflexos re duz à metade”. Em', 4, 'vez do normal, uma vez por rodada você pode gastar uma ação de movimento para proje tar uma labareda, num alvo em alcance curto. O alvo sofre 4d6 pontos de dano de Energia (Reflexos reduz à metade). como discente, mas muda o', 'LB'),
('cineraria', 'Cinerária', 'medo', 1, 'padrão', 'curto', NULL, 'nuvem de 6m de raio', 'cena', NULL, 2, 'Você manifesta uma névoa carregada de essência paranormal. Rituais conjurados dentro da névoa têm sua DT aumentada em +5. além do normal, rituais conjurados', 'LB'),
('compreensao-paranormal', 'Compreensão Paranormal', 'conhecimento', 1, 'padrão', 'toque', '1 ser ou objeto', NULL, 'cena', 'Vontade anula', 2, '(veja texto) O ritual confere a você compreensão sobrenatural da linguagem. Se tocar um objeto contendo informação (ou livro, um dispositivo com uma gravação…), você entende as palavras mesmo que não conheça seu', 'LB'),
('conhecendo-o-medo', 'Conhecendo o Medo', 'medo', 4, 'padrão', 'toque', '1 pessoa', NULL, 'instantânea', 'Vontade parcial', 8, 'Você manifesta medo absoluto na mente do alvo. Se ele falhar no teste de resistência, a Sanidade dele é reduzida a 0 e ele fica enlouquecendo. Se ele passar, sofre 10d6 pontos de dano mental e fica apavorado por 1 rodada. Uma pessoa que fique insana pelo efeito deste ritual se transforma em uma criatura paranormal a critério do mestre.', 'LB'),
('consumir-manancial', 'Consumir Manancial', 'morte', 1, 'padrão', 'pessoal', 'você', NULL, 'instantânea', NULL, 2, 'Você suga uma pequena porção do tempo de vida de plantas, insetos e até mesmo do solo ao redor, gerando Lodo e rece bendo 3d6 pontos de vida temporá rios. Os PV temporários desaparecem ao final da cena.', 'LB'),
('contato-paranormal', 'Contato Paranormal', 'conhecimento', 3, 'completa', 'pessoal', 'você', NULL, '1 dia', 'Reflexos anula', 6, 'Três laços de Energia surgem do chão e se enroscam no alvo, deixando-o agarrado. O alvo pode tentar se li vrar, gastando uma ação padrão para fazer um teste de Atletismo (DT do ritual). Se passar, destrói um laço, mais um laço adicional para cada 5 pontos pelos quais superou a DT. Os laços também podem ser atacados e destruídos: cada um tem Defesa 10, 10 PV, RD 5 e imunidade a Energia. Se todos os laços forem destruíd os, o ritual é dissipado. Por serem feitos de Energia, os laços afetam cria tu', 'LB'),
('controle-mental', 'Controle Mental', 'conhecimento', 4, 'padrão', 'médio', '1 pessoa ou animal', NULL, '', 'Vonta de parcial', 8, 'Você domina a mente do alvo, que obedece todos os seus co mandos, exceto or- dens sui cidas. Um alvo tem direito a um teste de Vonta- de no final de cada um de seus turnos para se livrar do efeito. Alvos que passarem no teste ficam pasmos por 1 rodada (apenas uma vez por cena).', 'LB'),
('convocar-o-algoz', 'Convocar o Algoz', 'morte', 4, 'padrão', '1,5m', '1 pessoa', NULL, 'sustentada', 'Vonta de parcial,', 8, 'Fortitude parcial Usando os medos subconscientes do alvo, você mani- pula a espiral da Morte para criar uma imagem daquilo que ele mais teme. Apenas a própria vítima vê o algoz com nitidez; outros seres pre sentes (incluindo você) enxer gam apenas um vulto sombrio. O algoz surge adjacente a você. No fim de cada turno seu, ele flutua 12m em direção à vítima. Se o algoz terminar o turno em alcance curto da vítima, ela deve fazer um teste de Vontade; se falhar, ficará abalada. Se o algoz terminar o', 'LB'),
('corpo-adaptado', 'Corpo Adaptado', 'sangue', 1, 'padrão', 'toque', '1 pessoa ou animal', NULL, 'cena', NULL, 2, 'Este ritual modifica a biologia do alvo para permitir a sobrevivência em ambientes hostis. O alvo fica imun e a calor e frio extrem os, pode respirar na água se respi- rar ar (ou vice-versa) e não sufoca em fumaça densa.', 'LB'),
('decadencia', 'Decadência', 'morte', 1, 'padrão', 'toque', '1 ser', NULL, 'instantâ nea', 'Fortitude reduz', 2, 'à metade Espirais de trevas envolvem sua mão e definham o alvo, que sofre 2d8+2 pontos de dano de Morte.', 'LB'),
('definhar', 'Definhar', 'morte', 1, 'padrão', 'curto', '1 ser', 'explosão de 15m de raio', 'cena', 'Fortitude parcial', 2, 'Você acumula uma quantidade imensa de Energia, então a libera em uma explosão intensa, como uma estrela em plena terra. Todos na área sofrem 3d10 x 10 pontos de dano de Energia e todos os itens tecno-', 'LB'),
('desacelerar-impacto', 'Desacelerar Impacto', 'morte', 2, 'reação', 'curto', NULL, NULL, 'até chegar ao solo ou', NULL, 4, 'cena, o que vier primeiro O alvo cai lentamente. A velocidade da queda é re- duzida para 18m por rodada — o suficiente para não causar dano. Como conjurar este ritual é uma reação, você pode conjurá-lo rápido o bastante para salvar a si ou um aliado de quedas inesperadas. Se o alvo for um projétil — como um disparo de arma ou um objeto largado do alto de um prédio —, o ritual faz com que ele cause metade do dano normal, devido à lentidão. Este ritual só funciona em alvos em queda livre ou simila', 'LB'),
('descarnar', 'Descarnar', 'sangue', 2, 'padrão', 'toque', NULL, NULL, 'instantânea', 'Fortitude parcial', 4, 'Este ritual cruel faz com que lacerações se manifestem na pele e órgãos do alvo, que sofre 6d8 pontos de dano (metade corte, metade Sangue) e fica com uma hemorragia severa. No início de cada turno dele, o alvo deve fazer um teste de Fortitude. Se falhar, sofre 2d8 pontos de dano de Sangue. Se passar nesse teste dois turnos seguidos, a hemorragia é estancada. Alvos que passem no teste de resistência inicial sofrem metade do dano e não ficam com hemorragia. muda o dano direto para 10d8 e', 'LB'),
('deteccao-de-ameacas', 'Detecção de Ameaças', 'conhecimento', 2, 'padrão', 'pessoal', NULL, 'esfera de 18m de raio', 'cena', NULL, 4, 'Você recebe uma percepção aguçada sobre perigos à sua volta. Quando um ser hostil ou armadilha entra na área do efeito, você tem uma sensação de perigo e pode gastar uma ação de movimento para fazer um teste de Percepção (DT 20). Se passar, sabe a direção e distância do perigo.', 'LB'),
('dissipar-ritual', 'Dissipar Ritual', 'medo', 3, 'padrão', 'médio', NULL, '1 ser ou objeto,', 'instantânea', NULL, 6, 'Você dissipa rituais ativos, como se a duração deles tivesse acabado. Efeitos de rituais instantâneos não podem ser dissipados (não se pode dissipar uma área de Paradoxo depois que já causou dano…). Faça um teste de Ocultismo; você anula quaisquer rituais ativos no alvo ou na área com DT igual ou menor que o resultado do teste. Você pode conjurar esse ritual em um item amaldiçoado para que se torne um item mundano (perdendo seus poderes) por um dia. Se o item estiver em posse de alguém, seu usuá', 'LB'),
('dissonancia-acustica', 'Dissonância Acústica', 'energia', 2, 'padrão', 'médio', 'veja texto', 'esfera com 6m de raio', 'veja texto', NULL, 4, 'Este ritual distorce o fluxo de tempo em relação a você, criando um pequeno bolsão temporal que dura 3 rodadas. Durante este tempo, você pode agir, mas não pode se deslocar do lugar nem interagir com seres e objetos. Da mesma forma, efeitos contínuos não o afetam, e quaisquer efeitos que você iniciar não afetarão a área ao seu redor. Efeitos de área com duração maior que este efeito vão agir normalmente quando o bolsão temporal acabar. Distorcer Aparência SANGUE 1 Execução: padrão Alcance: pesso', 'LB'),
('eco-espiral', 'Eco Espiral', 'morte', 2, 'padrão', 'curto', '1 ser', NULL, '2 rodadas', 'Fortitude reduz', 4, 'à metade Você manifesta em suas mãos uma pequena cópia do alvo feita de cinzas. No início do próximo turno após conjurar este ritual, você precisa gastar uma ação padrão para se concentrar nele; caso contrário, ele se dissipa sem efeito. No início do segundo turno, você precisa gastar uma ação padrão para descarregá-lo. Se fizer isso, a cópia explode e o alvo sofre dano de Morte igual a quantidade de dano que sofreu na ro- dada em que você se concentrou (Fortitude reduz à metade). Se não fizer, ', 'LB'),
('eletrocussao', 'Eletrocussão', 'energia', 1, 'padrão', 'curto', '1 ser ou objeto', NULL, 'instantâ nea', 'Fortitude parcial', 2, 'Você manifesta e dispara uma corrente elétrica contra o alvo, que sofre 3d6 pontos de dano de eletricidade e fica vulnerável por uma rodada. Se passar no teste de resistência, sofre apenas me tade do dano e evita a condição. Se usado contra objetos eletrônicos, este ritual causa o dobro de dano e ignora resistência.', 'LB'),
('embaralhar', 'Embaralhar', 'energia', 1, 'padrão', 'pessoal', 'você', NULL, 'cena', 'Vontade anula', 2, 'Este ritual torna o alvo prestativo (veja a página 45). Ele não fica sob seu con trole, mas percebe suas palavras e ações da maneira mais favorável possível. Você recebe um bônus de +10 em test es de Diplomacia com ele. Um alvo hostil ou que esteja envolvido em combate recebe +5 em seu teste de resistência. Se você ou seus aliados tom arem qualquer ação hostil contra o alvo, o efeito é dissipado e o alvo retor na à atitude que tinha antes (ou piora da, de acordo com o mestre). 131', 'LB'),
('esconder-dos-olhos', 'Esconder dos Olhos', 'conhecimento', 2, 'livre', 'pessoal', 'você', NULL, '1 rodada', NULL, 4, 'Você fica invisível, incluindo seu equipamento, recebendo camufla gem total e +15 em testes de Furti vidade. Como o normal, seres que não possam vê-lo ficam desprevenidos contra seus ataques. O efeito termina se você faz um ata que ou usa uma habilidade hostil. Ações contra objetos livres não dissip am Esconder dos Olhos (você pode tocar ou apanhar objetos que não estejam sendo segurados por outros seres). Cau sar dano indiretamente — por exem plo, preparar explosivos para detonar mais tarde — n', 'LB'),
('espirais-da-perdicao', 'Espirais da Perdição', 'morte', 1, 'padrão', 'curto', '1 ser', NULL, 'cena', NULL, 2, 'Espirais surgem no corpo do alvo, tornando seus mo- –O vimentos lentos. O alvo sofre em testes de ataque. –OO.', 'LB'),
('ferver-sangue', 'Ferver Sangue', 'sangue', 3, 'padrão', 'curto', '1 ser', NULL, 'sustentada', 'Fortitude parcial', 6, 'O sangue do alvo aquece até entrar em ebulição. Quando o ritual é conjurado, e no início de cada turno do alvo, ele deve fazer um teste de Fortitude. Se falhar, sofre 4d8 pontos de dano de Sangue e fica fraco; se passar, sofre metade do dano e não fica fraco nesta rodada. Se o alvo passar nesse teste dois turnos seguidos o efeito termina.', 'LB'),
('fim-inevitavel', 'Fim Inevitável', 'morte', 4, 'completa', 'extremo', NULL, NULL, '4 ro dadas', 'Fortitude parcial', 8, 'Você cria um vácuo em um espaço desocupado a sua escolha. No início de cada um de seus quatro turnos seguintes, todos os seres a até 90m do vácuo, incluin do você, devem fazer um teste de For titude. Em caso de falha, ficam caídas e são puxadas 30m na direção do vácuo. Objetos soltos também são pu- xados. Seres podem gastar uma ação de movimento para se segurar em algum objeto fixo, recebendo +5 em seus tes tes de resistência. Seres e objetos que', 'LB'),
('flagelo-de-sangue', 'Flagelo de Sangue', 'sangue', 2, 'padrão', 'toque', '1 pessoa', NULL, 'cena', 'Fortitude parcial', 4, 'Você toca uma pessoa, gravando uma marca escari- ficada no corpo dela enquanto profere uma ordem, como “não ataque a mim ou meus aliados”, “siga-me” ou “não saia desta sala”. A cada rodada que o alvo desobedecer a ordem, a marca inflige uma dor ex- cruciante, que causa 10d6 pontos de dano de Sangue e deixa o alvo enjoado pela rodada (Fortitude reduz o dano à metade e evita a condição). Se o alvo passar nesse teste dois turnos seguidos a marca desaparece.', 'LB'),
('forma-monstruosa', 'Forma Monstruosa', 'sangue', 3, 'padrão', 'pessoal', 'você', NULL, 'cena', NULL, 6, 'Seu corpo se transforma, assumindo uma forma que combina suas características com as de uma criatura de Sangue; suas roupas e proteção se mesclam à sua carne, transformando-se em uma couraça, e quaisquer objetos em suas mãos se fundem aos seus braços, transformando-se em garras pontiagudas. Seu equi- pamento fica inacessível, mas seus bônus se mantém. Seu tamanho muda para Grande e você recebe +5 em testes de ataque e rolagens de dano corpo a corpo e 30 PV temporários. Enquanto estiver transform', 'LB'),
('fortalecimento-sensorial', 'Fortalecimento Sensorial', 'sangue', 1, 'padrão', 'pessoal', 'você', NULL, 'cena', NULL, 2, '+O Você potencializa seus sentidos, recebendo em Investigação, Luta, Percepção e Pontaria.', 'LB'),
('hemofagia', 'Hemofagia', 'sangue', 2, 'padrão', 'toque', '1 ser', NULL, 'instantâ nea', 'Fortitude reduz', 4, 'à metade Você arranca o sangue do corpo do alvo através da pele dele, causando 6d6 pontos de dano de Sangue. Você então absorve esse sangue, recuperando pontos de vida iguais à metade do dano causado.', 'LB'),
('inexistir', 'Inexistir', 'conhecimento', 4, 'padrão', 'toque', '1 ser', NULL, 'instantânea', 'Vontade parcial', 8, 'Este é um ritual extremamente cruel, que já condenou grandes agentes da Ordem ao oblívio. Você toca o alvo com a intenção de apagá-lo por completo da existência, fazendo a mente e o corpo do alvo serem reescritos e desmantelados da existência. O alvo co- meça a levitar a poucos centímetros do chão e textos narrando todos os momentos de sua vida surgem e brilham por cima de sua pele, até que a existência dele começa a ser destruída de dentro, causando 10d12+10 pontos de dano de Conhecimento. Se o', 'LB'),
('invadir-mente', 'Invadir Mente', 'conhecimento', 2, 'padrão', 'médio ou toque', '1 ser ou 2 pessoas', NULL, '', 'Vontade parcial ou', 4, 'nenhuma Quando conjura este ritual, você gera um dos efeitos a seguir, a sua escolha: ra- jada mental (usa os primeiros parâmetros do cabe- çalho acima) ou ligação telepática (usa os segundos parâmetros). Rajada Mental: você infecta a mente do alvo com o Conhecimento proibido do Outro Lado, dilacerando o cérebro dele. O alvo sofre 6d6 pontos de dano de 134', 'LB'),
('involucro-de-carne', 'Invólucro de Carne', 'sangue', 4, 'padrão', 'curto', NULL, NULL, 'cena', NULL, 8, 'Você manifesta uma poça de sangue no chão, de onde emerge uma cópia sua. Ela é idêntica em aparência e capacidades (em termos de jogo, tem as mesmas estatísticas) e surge com uma cópia de todo equipa- mento mundano que você estiver carregando. A cópia não tem consciência (valor de Intelecto e Presença nulos) e não age sem que você dê uma ordem. Você pode gastar uma ação de movimento para dar uma ordem à cópia, como “lute contra aquele ser”. No final de cada um de seus turnos, a cópia segue a ord', 'LB'),
('lamina-do-medo', 'Lâmina do Medo', 'medo', 4, 'padrão', 'toque', '1 ser', 'círculo com 90m', 'instantâ nea', 'Fortitude parcial', 8, 'de raio Dura ção: cena Este ritual pode encontrar uma pessoa ou objeto a sua escolha. Você pode pensar em termos gerais (“um policial”, “algo de metal”) ou específicos (“A delegada Joana”, “uma pistola”). O ritual indica a direção e distân cia da pessoa ou objeto mais próxi- mo desse tipo, caso esteja ao alcance. Você pode movimentar-se para conti nuar procurando. Procurar algo mui to específico (“a chave do armazém 4 no porto”) exige que você tenha em mente uma imagem preci sa do objeto; caso a', 'LB'),
('luz', 'Luz', 'energia', 1, 'padrão', 'curto', '1 objeto', NULL, 'cena', NULL, 2, 'Resis tência: Vontade anula (veja texto) O alvo emite luz de cores alternadas e brilhantes (mas não produz ca lor) em uma área com 9m de raio. O objeto pode ser guardado (em um bol so, por exemplo) para interromper a luz, que voltará a funcionar caso o ob jeto seja revelado. Se o alvo for um objeto em posse de uma pessoa involuntá ria, ela tem direito a um teste de Von tade para anular o efeito.', 'LB'),
('medo-tangivel', 'Medo Tangível', 'medo', 4, 'padrão', 'pessoal', 'você', NULL, 'cena', NULL, 8, 'O ritual transforma seu corpo em uma manifestação do Medo, tornando-o imune a efeitos mundanos. Você fica imune às cond ições atordoado, cego, debilitado, en joado, envenenado, exausto, fatigad o, fraco, lento, 135', 'LB'),
('mergulho-mental', 'Mergulho Mental', 'conhecimento', 3, 'padrão', 'toque', '1 pessoa', NULL, '', 'Vontade parcial', 6, '(veja texto) Você mergulha nos pensamentos do alvo para desco- brir informações sobre ele. Durante o mergulho, você fica desprevenido. No início de cada turno seu que estiver sustentando o efeito e tocando o alvo, ele deve fazer um teste de Vontade. Se falhar, deve responder uma pergunta sua que possa ser respondida com “sim” ou “não”, sendo incapaz de mentir. O que você desco bre depende das suas perguntas e do mestre: talvez você não descubra tudo que há para saber, mas pode ganhar pistas para', 'LB'),
('miasma-entropico', 'Miasma Entrópico', 'morte', 2, 'padrão', 'médio', NULL, 'nuvem com 6m de raio', '', 'Fortit ude parcial', 4, '(veja texto) Cria uma explosão de emanações tóxicas. Seres na área sofrem 4d8 pontos de dano químico e ficam enjoados por 1 rodada. Se passarem na resistên cia, sofrem metade do dano e não fi cam enjoados.', 'LB'),
('nuvem-de-cinzas', 'Nuvem de Cinzas', 'morte', 1, 'padrão', 'curto', NULL, NULL, 'cena', NULL, 2, 'Uma nuvem de fuligem espessa eleva-se de um ponto a sua escolha, obscurecendo toda a visão — seres a até 1,5m têm camuflagem leve e seres a partir de 3m têm camuflagem total. Um vento forte dispersa a nuvem em 4 rodadas e um vendaval a dispersa em 1 rodada. A nuvem não funciona sob a água.', 'LB'),
('odio-incontrolavel', 'Ódio Incontrolável', 'sangue', 1, 'padrão', 'toque', '1 pessoa', NULL, 'cena', NULL, 2, 'O alvo entra em um frenesi, aumentando sua agressi- vidade e capacidade de luta. Ele recebe +2 em tes tes de ataque e rolagens de dano corpo a corpo e resistência a balístico, corte, impacto e perfuração 5. Enquanto o efeito durar, o alvo não pode fazer nenhuma ação que exige calma e concentração (como usar a perícia Furtividade ou conjurar rituais), e deve sempre atacar um alvo em sua rodada, mesmo que seja um aliado se ele for o único a seu alcance.', 'LB'),
('ouvir-os-sussurros', 'Ouvir os Sussurros', 'conhecimento', 1, 'completa', 'pessoal', 'você', NULL, 'instantânea', NULL, 2, 'O ritual conecta você com os sussurros, memórias ecoadas pelo Outro Lado, que você pode consultar para receber conhecimento proibido em relação a uma ação que tomará em breve. Ao usar este ritual, faça uma pergunta sobre um evento que você está prestes a fazer (na mesma cena) que possa ser respondida com “sim” ou “não”. O mestre rola 1d6 em segre do; com um resultado de 2 a 6, o ritual funciona e você recebe sua resposta, que pode ser “sim”, “não” ou “sim e não”. Com um resultado 1, o ritual fal', 'LB'),
('paradoxo', 'Paradoxo', 'morte', 2, 'padrão', 'médio', '1 pessoa', 'esfera com 6m de raio', '1 rodada', 'Fortitude reduz', 4, 'Resistência: Vontade anula Você dá uma ordem que o alvo deve ser capaz de ouvir (mas não precisa entender). Se falhar na resistência, ele deve obedecer à ordem em seu próprio turno da melhor maneira possível. Escolha um dos efeitos. Fuja: O alvo gasta seu turno tentando se afastar de você (usando todas as suas ações). Largue: O alvo solta quaisquer itens que esteja se- gurando e não pode pegá-los de volta até o início de seu próximo turno. Como esta é uma ação livre, ele ainda pode executar outr', 'LB'),
('poeira-da-podridao', 'Poeira da Podridão', 'morte', 3, 'padrão', 'médio', 'você', 'nuvem com 6m de raio', 'sustentada', 'Fortitude (veja texto)', 6, 'Resis tência: Vontade anula Você gera uma aura magnética sobrenatural. Escolha um dos efeitos a seguir. Atrair: você pode usar uma ação de movimento para puxar um objeto metálico de espaço 2 ou menor dentro do alcance. Se o objeto estiver livre, voa para suas mãos (caso tenha mãos livres para apanhá-lo) ou para seus pés. Repelir: você repele objetos de espaço 2 ou menor (o que envolve quase todos os projéteis e armas de arremesso), recebendo resistência a balístico, corte, impacto e perfuração 5', 'LB'),
('possessao', 'Possessão', 'conhecimento', 4, 'padrão', 'longo', '1 pessoa viva ou morta', NULL, '1 dia', 'Vontade anula', 8, 'Você projeta sua consciência no corpo de uma pessoa viva ou morta. Enquanto possuir o alvo, você assume o controle total do corpo dele (se o alvo estiver vivo, a consciência dele troca de lugar com a sua, ficando inerte dentro do seu corpo desacordado). Em ter- mos de jogo, você continua usando a sua ficha, mas com os atributos físicos (Agilidade, Força e Vigor) e deslocamento do alvo. Se o alvo passar no teste de resistência, sabe que você tentou possuí-lo e fica imune a este ritual por um dia.', 'LB'),
('presenca-do-medo', 'Presença do Medo', 'medo', 4, 'padrão', 'pessoal', '1 ser', 'emanação de 9m de raio', 'cena', NULL, 8, 'Você canaliza uma aura de Medo puro, que prote- ge o alvo contra efeitos paranormais. O alvo recebe resistência a dano paranormal 5 e +5 em testes de resistência contra rituais e habilidades de criaturas paranormais.', 'LB'),
('purgatorio', 'Purgatório', 'sangue', 3, 'padrão', 'curto', 'área de 6m de raio', NULL, 'sustentada', 'Fortitude parcial', 6, 'Você faz brotar uma poça de sangue pegajoso na área afetada. Inimigos na área se tornam vulneráveis a dano balístico, de corte, de impacto e de perfuração. Um alvo que tente sair da área é acometido de uma dor terrível; sofre 6d6 pontos de dano de Sangue e deve fazer um teste de Fortitude. Se passar, conse- gue sair. Se falhar, a dor faz com que não consiga se mover e perca a ação de movimento.', 'LB'),
('rejeitar-nevoa', 'Rejeitar Névoa', 'medo', 2, 'padrão', 'curto', NULL, 'nuvem de 6m de raio', 'cena', NULL, 4, 'Você manifesta um leve redemoinho de névoa que se movimenta suavemente dentro da área. Rituais conjurados dentro da área têm seu custo aumentado em +2 PE por círculo e sua execução aumentada em um passo (de livre para movimento, de movimento para padrão, de padrão para completa, de completa para duas rodadas). Rejeitar a Névoa anula os efeitos de Cinerária, a menos que o conjurador de Cinerária use uma ação completa por rodada para manter o ritual ativo, neutralizando o efeito dos dois rituais. ', 'LB'),
('salto-fantasma', 'Salto Fantasma', 'energia', 3, 'padrão', 'médio', 'você', NULL, 'instantânea', NULL, 6, 'Seu corpo se transforma momentaneamente em Ener- gia pura e viaja até outro ponto. Você não precisa per- ceber nem ter linha de efeito ao seu destino, podendo apenas imaginá-lo, desde que já tenha observado o local de alguma forma (em pessoa, por fotografia, por vídeo…). Por exemplo, pode se transportar 3m adiante para ultrapassar uma porta fechada. Uma vez transportado, você não pode agir pelo resto do seu turno. Este ritual não permite que você apareça dentro de um corpo sólido; se o ponto de ', 'LB'),
('sopro-do-caos', 'Sopro do Caos', 'energia', 2, 'padrão', 'médio', NULL, 'varia', '', 'veja texto', 4, 'Você altera os movimentos de massas de ar de forma caótica. Ao conjurar o ritual, escolha um dos efeitos abaixo. Ascender: cria uma corrente de ar ascendente capaz de erguer do chão um ser ou objeto Médio, fazendo o alvo flutuar para cima e para baixo conforme sua vontade. Você pode gastar uma ação de movimento para subir ou descer o alvo até 6m por rodada, até um máximo de 30m de altura. Você não pode mo- ver o alvo horizontalmente — mas o alvo pode, por exemplo, escalar uma colina ou se apoiar', 'LB'),
('tecer-ilusao', 'Tecer Ilusão', 'conhecimento', 1, 'padrão', 'médio', NULL, NULL, 'cena', NULL, 2, 'Resis tência: Vontade desacredita Este ritual cria uma ilusão visual (uma pessoa, uma parede…) ou sonora (um grito de socorro, um uivo assustador…). O ritual cria apenas imagens ou sons simples, com volume equivalente à voz de uma pessoa para cada cubo de 1,5m no efeito. Não é possível criar cheiros, texturas ou temperaturas, nem sons complexos, como uma música ou diálogo. Seres e objetos atravessam uma ilusão sem sofrer dano, mas o ritual pode, por exemplo, esconder uma armadilha ou emboscada. ', 'LB');



-- ============================================================
-- ITENS
-- ============================================================

-- Armas simples
INSERT INTO items (slug, name, item_type, spaces, damage, damage_type, critical, range_type, hands, description, source) VALUES
('faca', 'Faca', 'arma_simples', 1, '1d4', 'corte/perfuração', 19, 'curto', 1, 'Faca comum. Leve e versátil.', 'LB'),
('machadinha', 'Machadinha', 'arma_simples', 1, '1d6', 'corte', 20, 'corpo_a_corpo', 1, 'Machadinha de madeira e metal. Pode ser arremessada.', 'LB'),
('bengala', 'Bengala', 'arma_simples', 1, '1d4', 'impacto', 20, 'corpo_a_corpo', 1, 'Bengala reforçada. Discreta e útil.', 'LB'),
('arco-e-flecha', 'Arco e Flecha', 'arma_simples', 2, '1d6', 'perfuração', 20, 'longo', 2, 'Arco simples com flechas. Silencioso.', 'LB'),
('estilingue', 'Estilingue', 'arma_simples', 1, '1d4', 'impacto', 20, 'médio', 1, 'Estilingue artesanal. Usa pedras como projétil.', 'LB');

-- Armas táticas
INSERT INTO items (slug, name, item_type, spaces, damage, damage_type, critical, range_type, hands, description, source) VALUES
('pistola', 'Pistola', 'arma_tatica', 1, '1d12', 'balístico', 18, 'curto', 1, 'Pistola semi-automática padrão.', 'LB'),
('pistola-pesada', 'Pistola Pesada', 'arma_tatica', 1, '2d8', 'balístico', 18, 'curto', 1, 'Pistola de maior calibre. Mais dano, mais recuo.', 'LB'),
('espingarda', 'Espingarda', 'arma_tatica', 2, '2d8', 'balístico', 19, 'curto', 2, 'Espingarda pump. Devastadora em curta distância.', 'LB'),
('rifle', 'Rifle', 'arma_tatica', 2, '2d10', 'balístico', 19, 'longo', 2, 'Rifle de assalto automático padrão.', 'LB'),
('submetralhadora', 'Submetralhadora', 'arma_tatica', 2, '1d12', 'balístico', 19, 'médio', 2, 'Compacta e automática. Boa para combate urbano.', 'LB'),
('metralhadora', 'Metralhadora', 'arma_tatica', 3, '2d12', 'balístico', 18, 'longo', 2, 'Metralhadora pesada. Suporte à equipe.', 'LB'),
('faca-de-combate', 'Faca de Combate', 'arma_tatica', 1, '1d6', 'corte/perfuração', 18, 'curto', 1, 'Faca tática militar. Ágil e precisa.', 'LB');

-- Armas pesadas
INSERT INTO items (slug, name, item_type, spaces, damage, damage_type, critical, range_type, hands, description, source) VALUES
('lanca-chamas', 'Lança-Chamas', 'arma_pesada', 4, '4d10', 'fogo', 20, 'curto', 2, 'Área cone curto. Incendeia alvos. Criaturas de Sangue são vulneráveis.', 'LB'),
('lanca-granadas', 'Lança-Granadas', 'arma_pesada', 3, '4d8', 'impacto', 20, 'médio', 2, 'Projétil explode em área curta ao redor do ponto de impacto.', 'LB'),
('rifle-de-precisao', 'Rifle de Precisão', 'arma_pesada', 3, '3d12', 'balístico', 19, 'extremo', 2, '+5 em ataques ao usar ação de mira. Ideal para longa distância.', 'LB');

-- Proteções
INSERT INTO items (slug, name, item_type, spaces, damage, damage_type, critical, range_type, hands, description, source) VALUES
('colete-leve', 'Colete Leve', 'protecao', 1, NULL, NULL, NULL, NULL, 0, 'RD 5 contra balístico e corte. Não penaliza movimentação.', 'LB'),
('colete-pesado', 'Colete Pesado', 'protecao', 2, NULL, NULL, NULL, NULL, 0, 'RD 10 contra balístico, corte e impacto. –1 em testes de Agilidade.', 'LB'),
('escudo-balistico', 'Escudo Balístico', 'protecao', 2, NULL, NULL, NULL, NULL, 1, '+3 Defesa. RD 10 balístico enquanto empunhado.', 'LB');

-- Itens gerais
INSERT INTO items (slug, name, item_type, spaces, description, source) VALUES
('kit-medico', 'Kit Médico', 'geral', 1, 'Permite ação de interlúdio para curar 3d6+Medicina PV. 3 usos.', 'LB'),
('lanterna', 'Lanterna', 'geral', 1, 'Ilumina área em alcance médio. Funciona com pilhas (24h de uso).', 'LB'),
('algemas', 'Algemas', 'geral', 1, 'Algemar alguém exige teste de Crime ou Luta DT 15.', 'LB'),
('gravador', 'Gravador', 'geral', 1, 'Grava até 8 horas de áudio. Útil para investigações.', 'LB'),
('binoculo', 'Binóculo', 'geral', 1, '+5 em testes de Percepção para observar alvos distantes.', 'LB'),
('kit-arrombamento', 'Kit de Arrombamento', 'geral', 1, '+5 em testes de Crime para abrir fechaduras. 5 usos.', 'LB'),
('corda', 'Corda (15m)', 'geral', 2, 'Corda resistente de 15 metros. Suporta até 200kg.', 'LB'),
('explosivo-caseiro', 'Explosivo Caseiro', 'geral', 2, 'Detonação: 4d8 impacto em área curta. Instável — pode detonar ao ser impactado (20% chance).', 'LB'),
('coquetel-molotov', 'Coquetel Molotov', 'geral', 1, 'Arremesso (alcance curto). 2d6 fogo por rodada em área curta. Dura 2 rodadas.', 'LB'),
('radio-chiador', 'Rádio Chiador', 'geral', 1, 'Detecta criaturas paranormais em alcance extremo. Chiado aumenta conforme proximidade.', 'SaH'),
('kit-sobrevivencia', 'Kit de Sobrevivência', 'geral', 2, 'Inclui fósforos, filtro d''água, cobertor de emergência e sinalizador. Essencial em missões no campo.', 'SaH');

-- Itens paranormais/amaldiçoados
INSERT INTO items (slug, name, item_type, element, curse_category, spaces, description, special_rules, prestige_required, source) VALUES
('oculos-da-verdade', 'Óculos da Verdade', 'paranormal', 'conhecimento', 1, 1,
  'Óculos de lentes douradas que revelam a natureza verdadeira das coisas.',
  'Ao usar, você pode ver auras paranormais e identificar elementos de criaturas a olho nu. Também detecta mentiras (Ocultismo DT 15). Custo: 1 PE por cena de uso.',
  0, 'LB'),

('luvas-de-sangue', 'Luvas de Sangue', 'paranormal', 'sangue', 2, 1,
  'Luvas negras impregnadas com sangue do Outro Lado. Umedecidas permanentemente.',
  'Ataques desarmados causam +2d6 Sangue. Uma vez por cena, pode gastar 3 PE para realizar Toque da Agonia sem precisar conhecer o ritual.',
  1, 'LB'),

('amuleto-da-morte', 'Amuleto da Morte', 'paranormal', 'morte', 1, 1,
  'Um pingente feito de osso humano com runas entalhadas à mão.',
  'Portador recebe resistência 10 a Morte. Uma vez por missão, pode retornar de 0 PV com 1 PV (a Morte cobrou seu preço — perde 1 ponto de Sanidade permanentemente).',
  0, 'LB'),

('capacete-espectral', 'Capacete Espectral', 'paranormal', 'morte', 2, 2,
  'Capacete translúcido que parece ser feito de névoa solidificada.',
  'RD 10 contra dano mental. +5 em testes de Vontade. O portador pode perceber seres incorpóreos adjacentes mesmo que estejam invisíveis.',
  1, 'LB'),

('adaga-de-sangue', 'Adaga de Sangue', 'paranormal', 'sangue', 3, 1,
  'Uma adaga cuja lâmina parece viva, pulsando vermelho e nunca secando.',
  'Dano 1d8+3 Sangue. Acertos críticos causam sangramentos que drenam 1d6 PV por rodada. Portador que a usa perde 1d4 PV no início de cada cena — a adaga alimenta a si mesma.',
  2, 'LB'),

('sanfona-de-pele-humana', 'Sanfona de Pele Humana', 'amaldicado', 'medo', 4, 3,
  'Um instrumento musical construído com pele humana curtida. Emite sons perturbadores.',
  'Ao tocar por 1 rodada, todos em alcance médio devem fazer Vontade DT 20 ou ficar apavorados por 1d4 rodadas. Tocar por mais de 1 hora começa a afetar o próprio tocador permanentemente.',
  3, 'AS1'),

('centrifugador-existencial', 'Centrifugador Existencial', 'paranormal', 'conhecimento', 3, 2,
  'Um dispositivo metálico vitoriano que converte correntes elétricas em estímulos cerebrais.',
  'Ao sofrer 5+ de dano elétrico ou Energia, recupera 1 PE (máximo 2x Vigor por dia). Uma vez por cena, pode gastar 5 PE para ganhar +5 em qualquer teste de perícia até o fim da rodada.',
  2, 'AS1'),

('ampulheta-do-tempo', 'Ampulheta do Tempo Sofrido', 'paranormal', 'morte', 3, 2,
  'Uma ampulheta cujo interior contém desespero visível como névoa escura.',
  'Ao segurar, pode gastar 5 PE para receber imediatamente os benefícios de uma ação de interlúdio à escolha. Só pode ser usada novamente após gastar uma ação de interlúdio para "devolver o tempo".',
  2, 'SaH'),

('instantaneo-mortal', 'Instantâneo Mortal', 'paranormal', 'morte', 2, 1,
  'Uma fotografia ou imagem que retrata o último momento de vida de uma pessoa.',
  'Ao segurar e gastar 1 PE em testes de perícia relacionados à imagem, recebe +5. Em investigações relacionadas à morte retratada, recebe +10.',
  1, 'SaH'),

('projetil-de-lodo', 'Projétil de Lodo', 'paranormal', 'morte', 2, 1,
  'Projétil forjado com Lodo do Outro Lado. Carrega a Morte consigo.',
  'Munição paranormal. Ataques com esta munição causam +2d6 Morte extra. Criaturas com invisibilidade, incorporeidade ou camuflagem perdem essas propriedades ao ser atingidas.',
  1, 'SaH');

-- ============================================================
-- PODERES
-- ============================================================

INSERT INTO powers (slug, name, power_type, nex_required, prerequisites, description, source) VALUES

-- Gerais
('ataque-preciso', 'Ataque Preciso', 'geral', 5, NULL,
  'Uma vez por rodada, você pode gastar 1 PE para receber +5 no próximo teste de ataque até o fim do turno.',
  'LB'),
('esquiva', 'Esquiva', 'geral', 5, NULL,
  'Uma vez por rodada, quando é alvo de um ataque, pode gastar 1 PE como reação para adicionar +5 à sua Defesa contra aquele ataque.',
  'LB'),
('vigor-sobrenatural', 'Vigor Sobrenatural', 'geral', 10, 'VIG 2',
  'Seus pontos de vida máximos aumentam em +10. Esse bônus aumenta para +20 em NEX 30% e +30 em NEX 60%.',
  'LB'),
('reflexos-aguçados', 'Reflexos Aguçados', 'geral', 5, 'AGI 2',
  'Você recebe +5 em testes de Iniciativa e Reflexos.',
  'LB'),
('tiro-certeiro', 'Tiro Certeiro', 'geral', 10, 'treinado em Pontaria',
  'Quando usa a ação de mira, recebe +5 no teste de ataque (em vez de +2). Em NEX 30%, o bônus aumenta para +10.',
  'LB'),
('combate-defensivo', 'Combate Defensivo', 'geral', 5, 'INT 2',
  'Quando usa a ação agredir, você pode combater defensivamente: sofre –1d no teste de ataque mas recebe +5 na Defesa até seu próximo turno.',
  'LB'),
('primeiros-socorros-avancados', 'Primeiros Socorros Avançados', 'geral', 5, 'treinado em Medicina',
  'Quando usa um kit médico, o alvo recupera PV adicionais iguais à sua Medicina. Você pode usar o kit médico sem gastar um uso se passar em Medicina DT 20.',
  'LB'),
('ocultismo-rapido', 'Ocultismo Rápido', 'geral', 5, 'treinado em Ocultismo',
  'Você pode fazer um teste de Ocultismo como ação livre uma vez por cena para identificar uma criatura ou item paranormal.',
  'LB'),

-- Combatente
('ataque-especial', 'Ataque Especial', 'combatente', 5, NULL,
  'Quando faz um ataque, você pode gastar PE (limitado pelo NEX) para receber bônus: NEX 5% (2 PE, +5), NEX 25% (3 PE, +10), NEX 55% (4 PE, +15), NEX 85% (5 PE, +20).',
  'LB'),
('resistencia-fisica', 'Resistência Física', 'combatente', 10, 'VIG 2',
  'Você recebe RD 5 contra dano físico. Em NEX 30%, aumenta para RD 10. Em NEX 60%, aumenta para RD 15.',
  'LB'),
('investida-furiosa', 'Investida Furiosa', 'combatente', 15, 'FOR 2',
  'Você pode gastar 2 PE para fazer uma investida como ação de movimento e ainda realizar a ação agredir normalmente.',
  'LB'),
('artilheiro', 'Artilheiro', 'combatente', 10, 'treinado em Pontaria',
  'Você ignora a penalidade por atirar em combate corpo a corpo. Ao usar armas automáticas, pode atirar em área curta com um único ataque.',
  'LB'),

-- Especialista
('perito', 'Perito', 'especialista', 5, NULL,
  'Você pode gastar 2 PE para receber +1d6 em um teste de perícia. O bônus aumenta conforme o NEX: NEX 25% (+1d8), NEX 55% (+1d10), NEX 85% (+1d12).',
  'LB'),
('ecletico', 'Eclético', 'especialista', 5, NULL,
  'Você pode gastar 2 PE para receber os benefícios de ser treinado em qualquer perícia até o fim da cena.',
  'LB'),
('mente-rapida', 'Mente Rápida', 'especialista', 10, 'INT 2',
  'Uma vez por cena, pode gastar 2 PE para fazer qualquer teste de Intelecto como ação livre.',
  'LB'),

-- Ocultista
('escolhido-pelo-outro-lado', 'Escolhido pelo Outro Lado', 'ocultista', 5, NULL,
  'Você aprendeu a manipular o Outro Lado. Pode lançar rituais de 1º círculo. Em NEX 25%, aprende rituais de 2º círculo. Em NEX 55%, de 3º círculo. Em NEX 85%, de 4º círculo.',
  'LB'),
('transcender', 'Transcender', 'ocultista', 10, 'Escolhido pelo Outro Lado',
  'Para se conectar com o Outro Lado, você pode meditar por 10 minutos para recuperar PE adicionais iguais à sua Presença.',
  'LB'),
('ritual-intenso-poder', 'Ritual Intenso', 'ocultista', 10, 'Escolhido pelo Outro Lado',
  'Uma vez por cena, pode gastar 2 PE adicionais ao lançar um ritual para aumentar sua DT em +5 e seu dano em +2d6.',
  'AS1'),
('saude-sobrenatural', 'Saúde Sobrenatural', 'ocultista', 15, 'Transcender',
  'Seu vínculo com o Outro Lado fortalece seu corpo. PV máximos aumentam em +Presença × 2. Uma vez por missão, pode se curar de uma condição permanente.',
  'AS1'),
('acostumado-a-maldicao', 'Acostumado à Maldição', 'ocultista', 20, 'Escolhido pelo Outro Lado',
  'Você passou tanto tempo exposto ao Outro Lado que seu corpo adaptou-se. Resistência 5 a um elemento à escolha. Em NEX 40%, escolhe um segundo elemento.',
  'AS1'),
('reter-ritual-de-combate', 'Reter Ritual de Combate', 'ocultista', 15, 'Escolhido pelo Outro Lado',
  'Você pode preparar um ritual como ação completa e liberá-lo como reação ou ação livre até o fim da cena seguinte.',
  'AS1'),

-- Paranormais — Sangue
('fraqueza-do-inimigo', 'Fraqueza do Inimigo (Sangue)', 'paranormal', 10, 'afinidade Sangue',
  'Você sente instintivamente as vulnerabilidades físicas dos inimigos. Uma vez por cena, pode gastar 2 PE para fazer um ataque que ignora completamente a RD e resistências do alvo.',
  'LB'),
('sangue-como-escudo', 'Sangue como Escudo', 'paranormal', 15, 'afinidade Sangue',
  'Você pode usar seu próprio sangue como barreira. Ao ser atacado, pode gastar 3 PE como reação para receber RD 15 contra aquele ataque.',
  'LB'),

-- Paranormais — Morte
('presenca-da-morte', 'Presença da Morte', 'paranormal', 10, 'afinidade Morte',
  'Sua presença perturba os vivos. Criaturas de até VD 20 em alcance curto precisam fazer Vontade DT Pre ou ficam abaladas por 1 rodada no início de cada cena.',
  'LB'),
('ver-os-mortos', 'Ver os Mortos', 'paranormal', 5, 'afinidade Morte',
  'Você pode ver e se comunicar com espíritos dos mortos. Pode gastar 1 PE para fazer perguntas sim/não a um espírito próximo.',
  'LB'),

-- Paranormais — Conhecimento
('absorcao-de-conhecimento', 'Absorção de Conhecimento', 'paranormal', 10, 'afinidade Conhecimento',
  'Uma vez por cena, ao tocar um objeto ou local, pode gastar 2 PE para receber uma visão de memórias ou eventos recentes relacionados a ele.',
  'LB'),
('mente-de-cristal', 'Mente de Cristal', 'paranormal', 15, 'afinidade Conhecimento',
  'Sua mente é impenetrável. Você é imune a efeitos de telepatia e leitura de mente. Além disso, +10 em testes de Vontade contra efeitos de Conhecimento.',
  'LB'),

-- Paranormais — Energia
('canalizar-energia', 'Canalizar Energia', 'paranormal', 10, 'afinidade Energia',
  'Uma vez por cena, você pode absorver Energia do ambiente. Se estiver em local com eletricidade, recupera 1d6+Pre PE.',
  'LB'),
('sobrecarga', 'Sobrecarga (Energia)', 'paranormal', 15, 'afinidade Energia',
  'Você pode sobrecarregar dispositivos eletrônicos adjacentes, fazendo-os explodir. Dano 3d8 Energia em área curta (Reflexos DT Pre reduz à metade).',
  'LB'),

-- Paranormais — Medo
('alimentar-se-do-medo', 'Alimentar-se do Medo', 'paranormal', 10, 'afinidade Medo',
  'Você se alimenta do terror alheio. Sempre que um ser próximo é apavorado, fica abalado ou sofre dano mental, você recupera 1d4 PE.',
  'LB'),
('presenca-apavorante', 'Presença Apavorante', 'paranormal', 15, 'afinidade Medo',
  'Você irradia terror sobrenatural. Uma vez por cena, todos em alcance curto devem fazer Vontade DT Pre ou ficam apavorados por 1d4 rodadas.',
  'LB'),

-- Intenção
('intencao-sobreviver', 'Sobreviver', 'intencao', 5, NULL,
  'Sua intenção é sobreviver a qualquer custo. Uma vez por missão, quando seria reduzido a 0 PV, você permanece com 1 PV.',
  'LB'),
('intencao-proteger', 'Proteger', 'intencao', 5, NULL,
  'Sua intenção é proteger os outros. Quando um aliado adjacente é alvo de um ataque, pode gastar 1 PE como reação para desviar o ataque para si mesmo.',
  'LB'),
('intencao-conhecer', 'Conhecer', 'intencao', 5, NULL,
  'Sua intenção é desvendar os mistérios do Outro Lado. Uma vez por sessão, pode fazer uma pergunta sobre o sobrenatural ao mestre, que deve responder com uma dica verdadeira.',
  'LB');

-- ============================================================
-- ORIGENS
-- ============================================================

INSERT INTO origins (slug, name, description, skills_granted, power_name, power_description, source) VALUES

('academico', 'Acadêmico',
  'Você passou anos em universidades estudando fenômenos inexplicáveis. Seja em história, ciências ou humanidades, sua vida girou em torno do saber.',
  '["Atualidades","Ciências","Investigação","Ocultismo"]',
  'Raciocínio Rápido',
  'Você pode fazer um teste de Atualidades ou Ciências como ação livre uma vez por cena para se lembrar de uma informação útil.',
  'LB'),

('agente-de-saude', 'Agente de Saúde',
  'Médico, enfermeiro ou paramédico — você passou anos lidando com o pior que a humanidade pode sofrer. Isso te preparou para o que nenhuma faculdade poderia.',
  '["Medicina","Fortitude","Ciências"]',
  'Atendimento Rápido',
  'Você pode estabilizar um ser morrendo como ação livre (em vez de ação padrão). Além disso, quando usa um kit médico, cura 1d6 PV adicionais.',
  'LB'),

('amnesico', 'Amnésico',
  'Você não sabe quem é. Fragmentos de memórias surgem em sonhos, mas a conexão com seu passado foi severdada. Algo terrível aconteceu — você só não sabe o quê.',
  '["Investigação","Percepção"]',
  'Memória Fragmentada',
  'Uma vez por sessão, você pode "se lembrar" de algo do seu passado que seja conveniente para a situação atual. O mestre determina os detalhes do que você se lembra.',
  'LB'),

('artista', 'Artista',
  'Pintor, músico, escritor, ator — sua arte é sua forma de processar o mundo. Você vê padrões e beleza onde outros veem caos, e isso inclui o paranormal.',
  '["Artes","Enganação","Percepção"]',
  'Inspiração Sombria',
  'Quando cria arte em uma cena de interlúdio relacionada a eventos paranormais que vivenciou, você e seus aliados recuperam 1d6 SAN adicional.',
  'LB'),

('atleta', 'Atleta',
  'Seu corpo foi forjado pelo esporte. Velocidade, resistência e reflexos acima da média são as ferramentas que o mundo normal lhe deu — e que valem muito no sobrenatural.',
  '["Atletismo","Acrobacia","Fortitude"]',
  'Corpo em Movimento',
  'Seu deslocamento aumenta em +3m. Além disso, você pode gastar 2 PE para dobrar seu deslocamento por uma rodada.',
  'LB'),

('chef', 'Chef',
  'A culinária é mais do que alimentação — é alquimia. Você aprendeu que os ingredientes certos, combinados da forma certa, podem criar algo extraordinário. Nem sempre isso é metáfora.',
  '["Profissão (chef)","Ciências","Percepção"]',
  'Fome do Outro Lado',
  'Você pode usar partes de criaturas do Outro Lado como ingredientes. Uma vez por missão, pode preparar um prato especial que concede RD 10 contra o elemento da criatura usada a um aliado.',
  'LB'),

('criminoso', 'Criminoso',
  'Seja como ladrão, assassino ou simplesmente alguém que viveu nas margens — você conhece as regras não escritas do mundo sombrio. E sabe como quebrá-las.',
  '["Crime","Enganação","Furtividade","Intimidação"]',
  'Conexões Duvidosas',
  'Uma vez por missão, você pode acionar suas conexões criminosas para obter itens de categoria I sem custo de prestígio, ou informações sobre o submundo local.',
  'LB'),

('cultista-arrependido', 'Cultista Arrependido',
  'Você conheceu o Outro Lado de um jeito que a maioria jamais conhecerá — de dentro. Pertenceu a um culto. Sabe como eles pensam. Sabe o que fazem. E carrega isso.',
  '["Ocultismo","Religião","Enganação"]',
  'Conhecimento Proibido',
  'Você tem acesso a conhecimento cultista. Uma vez por missão, pode identificar rituais, símbolos ou práticas de cultos específicos sem precisar de teste.',
  'LB'),

('desgarrado', 'Desgarrado',
  'Você não tem lugar, família ou passado estável. A vida nômade e difícil te ensinou que a única pessoa em quem você pode confiar é você mesmo. E às vezes nem isso.',
  '["Sobrevivência","Fortitude","Atletismo"]',
  'Instinto de Sobrevivência',
  'Quando está com metade ou menos dos PV, você recebe +2 em todos os testes de ataque e defesa.',
  'LB'),

('investigador', 'Investigador',
  'Repórter, detetive particular, jornalista investigativo — sua vida é fazer perguntas que outros têm medo de fazer. E encontrar respostas que outros preferem não conhecer.',
  '["Investigação","Percepção","Enganação","Atualidades"]',
  'Farejador de Pistas',
  'Quando procura pistas em uma cena de investigação, pode fazer dois testes e ficar com o melhor resultado. Além disso, sempre sabe quando está sendo enganado (Vontade DT 15 para detectar mentiras).',
  'LB'),

('lutador', 'Lutador',
  'Artes marciais, boxe, luta livre — não importa o estilo. Seu corpo é sua arma, e você passou anos afiando-o.',
  '["Luta","Atletismo","Fortitude"]',
  'Artista Marcial',
  'Seus ataques desarmados causam 1d6 de dano (em vez de 1d3), podem causar dano letal e são considerados ágeis.',
  'LB'),

('militar', 'Militar',
  'Exército, marinha, aeronáutica — você serviu. Viu coisas que civis jamais deveriam ver. E agora enfrenta algo ainda pior.',
  '["Luta","Pontaria","Fortitude","Tática"]',
  'Treinamento Tático',
  'Uma vez por cena, pode gastar 1 PE para fornecer +2 em todos os testes de um aliado que possa ver e ouvir suas instruções até seu próximo turno.',
  'LB'),

('policial', 'Policial',
  'Você jurou proteger. Mas o que você encontrou nas ruas — nos casos mais sombrios que nenhum relatório descreve corretamente — mudou para sempre o que você entende por "proteger".',
  '["Investigação","Intimidação","Luta","Pontaria"]',
  'Autoridade',
  'Você recebe +5 em testes de Intimidação e Diplomacia com pessoas comuns. Uma vez por cena, pode gastar 2 PE para obrigar um NPC a responder uma pergunta com verdade (Vontade DT Pre para resistir).',
  'LB'),

('religioso', 'Religioso',
  'Padre, pastor, espírita, umbandista, monge — sua fé foi sua âncora. E quando o Outro Lado apareceu, você precisou decidir: a fé te protege ou é apenas mais uma ilusão confortável?',
  '["Religião","Diplomacia","Vontade"]',
  'Fé Inabalável',
  'Você recebe +5 em testes de Vontade contra efeitos de medo e dano mental. Uma vez por missão, pode rezar por 1 minuto para recuperar 1d6 SAN.',
  'LB'),

('vitima', 'Vítima',
  'O paranormal não te escolheu — te encontrou. Você era uma pessoa normal. Viu algo que não deveria. E agora não tem escolha senão seguir em frente.',
  '["Percepção","Fortitude"]',
  'Trauma como Força',
  'Quando é alvo de um efeito de medo ou dano mental, pode gastar 1 PE como reação para reduzir o dano ou o efeito pela metade. Seu sofrimento passou a ser sua armadura.',
  'LB'),

-- Arquivos Secretos
('ferido-por-ritual', 'Ferido por Ritual',
  'Um ritual que não deveria ter acontecido te atingiu. Talvez você fosse o alvo. Talvez fosse apenas dano colateral. De qualquer forma, o Outro Lado deixou sua marca permanente no seu corpo.',
  '["Ocultismo","Fortitude","Vontade"]',
  'Cicatriz Paranormal',
  'Você carrega uma cicatriz de ritual que reage ao sobrenatural. Quando está a alcance curto de uma criatura paranormal ou ritual ativo, você sente fisicamente (dor, calor, frio). Além disso, recebe +5 em testes de Vontade contra rituais.',
  'AS1'),

('transtornado-arrependido', 'Transtornado Arrependido',
  'Você foi um Transtornado — uma criatura à beira da transformação pelo Outro Lado. Mas algo te trouxe de volta. Quase. As marcas ainda estão lá, dentro de você.',
  '["Ocultismo","Fortitude","Intimidação"]',
  'Natureza Limiar',
  'Você está no limiar entre humano e criatura. Uma vez por missão, pode "abraçar" temporariamente o Outro Lado: por 1 cena, ganha +4 em Força e Vigor e resistência 10 a dano físico, mas sofre -2 em Intelecto e Presença.',
  'AS1'),

('fanatico-por-criaturas', 'Fanático por Criaturas',
  'Você sempre foi obcecado pelo sobrenatural. Desde criança, buscava criaturas em documentários sensacionalistas. Até encontrá-las de verdade.',
  '["Investigação","Ocultismo","Percepção"]',
  'Conhecimento Oculto',
  'Você pode fazer testes de Ocultismo para identificar criaturas a partir de imagens, rastros ou indícios. Se passar, descobre as características da criatura. Quando identifica uma criatura, recebe +2 em todos os testes contra ela até o fim da missão.',
  'SaH');